service: 
  name: ${self:custom.NAME}
useDotenv: true
frameworkVersion: ">=1.48.1"
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: pixela
  environment:
    ADMIN_JWT_SECRET: ${self:custom.ADMIN_JWT_SECRET}
custom:
  NAME: strapi-serverless
  ADMIN_JWT_SECRET: ${env:ADMIN_JWT_SECRET, ''}
package:
  exclude:
    - ./**
  include:
    - api/**
    - app.js
    - config/**
    - extensions/**
    - node_modules/**
    - package.json
    - plugins/**
    - server/**
functions:
  handler:
    handler: server/handler.handler
    # memorySize: 1024
    # timeout: 24
    events:
      - http:
          path: '/'
          method: get
          cors: true
      - http: ANY {proxy+}
plugins:
  - serverless-offline